### ISSUE TITLE
Custom APEX export options

### ISSUE THREAD

**Issue by brMichael** [MaikMichel/dbFlux#11]
Besides the APEX export options given in dbFlux (skipExportDate and split), it would be nice to be able to customize these options in the vscode workspace settings for dbFlux.
Other projects might require to export e.g. private report settings or developer comments or might want to export in a different format (e.g. READABLE_JSON).

**Comment by MaikMichel** [comment]
you can do that by configuring the export setting `Append Following Option String`

![image](https://github.com/MaikMichel/dbFlux/assets/12570539/93b589db-1b3e-4eb6-9f44-fdb6bb987cb3)
