### ISSUE TITLE
TreeView - Error when removing the last table per "**X**" -  if more than one table was previously in the panel.

### ISSUE THREAD

**Issue by scl-4711** [MaikMichel/dbFlux#12]
![image](https://github.com/MaikMichel/dbFlux/assets/12970066/bd2d3d77-982a-407a-9611-ad807a934749)

Error occurs when removing the last table per "**X**" -  if more than one table was previously in the panel.

**Comment by MaikMichel** [comment]
Hey Claus, thanks for reporting. I'll have a look at it ;-)
