### ISSUE TITLE
Add Table to Column-Viewer appears twice in the menu

### ISSUE THREAD

**Issue by scl-4711** [MaikMichel/dbFlux#13]
![image](https://github.com/MaikMichel/dbFlux/assets/12970066/56f14b07-0454-4626-aef6-18e0b1f18b86)

A small issue ;-)

**Comment by MaikMichel** [comment]
Hi Steffen, you are fast ;-) 
Thank you for reporting. The command in your screenshot is not  doubled. It's a special one. But you are right it should not be visible in the command palette. This one and some new ones are all dedicated to the new treeview.
