### ISSUE TITLE
Individuelle Namen für Datenbank-Schema und Workspace

### ISSUE THREAD

**Issue by madmexx2002** [MaikMichel/dbFlux#4]
Hallo Maik

Dein Beitrag in der Red Stack über dbFlux kam genau richtig. Die neusten Sicherheitsrichtlinien verhindern den Download von JS Dateien aus den Shared Components und der "Download as Zip" Button tut nichts. Laut DB-Betrieb ein Apex Bug (?). Hier könnte dbFlux die Lücke schließen und gewaltig Zeit im täglichen gebrauch sparen. Glückwunsch, geiles Werkzeug erdacht!

Wenn man selbst DBA-Rechte hat kann man gut damit leben das hier vorgedachte Namen vergeben werden. Allerdings in meinem Fall werden die Schema- und Workspacenamen vom Datenbankbetrieb vergeben, bzw. abgeleitet. 

Idee: Ich fände es gut wenn der Schema- und Workspacenamen während der Projekterstellung festgelegt werden könnten. Somit könnte dbFlux auch für bereits bestehnde Apex-Installationen verwendet werden.

Frage: Besteht die Möglichkeit diese Parameter im Workspace-Speicher zu verändern?

Gruß Mark

**Comment by MaikMichel** [comment]
Hi Mark,

Danke für dein Feedback. Aktuell kannst du für die Schemas benennen wir du willst. Dazu musst du einfach in der **build.env** die jeweiligen Variablen bestücken und dann die Verzeichnissenamen entsprechend anpassen. Derzeit arbeite ich an einem Feature, in dem dieser Schritt wegfällt und man frei x-beliebige Verzeichnisse nehmen kann.

Den Workspacenamen kannst du in der **build.env** ebenfalls anpassen.

Viele Grüße, Maik

**Comment by madmexx2002** [comment]
Hi Maik

Vielen Dank für die schnelle Antwort. Wie, bzw. wo kann ich diese build.env auf einem Windows System finden? 

Gruß Mark

**Comment by MaikMichel** [comment]
Hi Mark,

wenn du die Verzeichnisstruktur via dbFlux angelegt hast, dann gibt es **noch**  keine Möglichkeit die Schemanamen zu ändern... (Demnächst werden die Schema allein durch das Vorhandensein als Ordner definiert).

Hast du die Verzeichnisstruktur via dbFlow (schau mal in neinen andere Repos) angelegt, findes du die build.env im Root-Ordner des Projektes.
- First: Add dbFlow as a submodul to your project
`git submodule add https://github.com/MaikMichel/dbFlow.git .dbFlow`

- Second: Create an inital project structur by calling
`.dbFlow/setup.sh generate <project_name>`

> This will start a wizard which prompts you some question concerning your desired project structure

Viele Grüße, Maik

**Comment by madmexx2002** [comment]
Hallo Maik

Mit dbFlow hat es geklappt. Allerdings bevorzuge ich der einfachheit wegen dbFlow. Der Ausblick auf die zukünftige Weiterentwicklung hört sich gut an. Ticket darf geschlossen werden.

Vielen Dank
Gruß Mark
