### ISSUE TITLE
Export Static Application Files

### ISSUE THREAD

**Issue by madmexx2002** [MaikMichel/dbFlux#6]
Hallo Maik

Ich habe dbFlow konfiguriert und den Ordner in VS Code geöffnet. dbFlux hat den Order erkannt und zeigt mir in der Statusbar "dbFlow" an. Static Files lassen sich bequem in die Datenbank hochladen. Soweit, so gut.

Die Funktion dbFlux: Export Static Application Files jedoch führt zu einem Fehler und es werden keine Dateien geladen.
Hier ist die Ausgabe vom Terminal
```
Connection:    developer_app/localhost:1521/pdb1
AppID:         129
File:
Target:        static/f129/src
15.09.2022 18:33:25 >> exporting Files from 129 to static/129/src 
15.09.2022 18:33:25 >> ... this may take a while 
Picked up JAVA_TOOL_OPTIONS: -Duser.language=en -Duser.region=US -Dfile.encoding=UTF-8
15.09.2022 18:33:29 >> Decoding exported static file ... 
15.09.2022 18:33:29 >> Unzipping exported schema file ... 
Archive:  static/f129/src.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of static/f129/src.zip or
        static/f129/src.zip.zip, and cannot find static/f129/src.zip.ZIP, period.
15.09.2022 18:33:29 >> export done
```
Ich verwende Windows10. Pfadnamen enthalten keine Leerzeichen.

Hast Du eine Idee was hier schief läuft?

Gruß Mark

**Comment by MaikMichel** [comment]
Hi Mark,

I can reproduce your issue when I use SQLcl. When I use SQLPlus it is working. The script seems to produce invalid base64 output on SQLcl. So as a workaround try to use SQLPlus.
Meanwhile I will try to fix that.

Many regards, 
Maik

**Comment by MaikMichel** [comment]
Hi Mark,
you have to change that inside VSCode Settings for the workspace or for the user. Just search for dbFlux when you are on the settings page. I think the first option should be the one.
Keep in mind that changing the SQLcli in apply.env only affects the way you apply the patches built with dbFlow. 
Are you in Nürnberg at the DOAG Conference? I will give a talk concerning both topics dbFlux as well as dbFlow...
Best regards,
Maik

**Comment by madmexx2002** [comment]
Hi Maik

Now it is working. Thx for the help. 
Even though NBG is just around the corner, I didn't book this year.

Regards

Mark
